/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kawemon.GUI;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Uer
 */
public class HomeBase extends javax.swing.JFrame {
    private JPopupMenu itemSellerMenu;
    /**
     * Creates new form HomeBase
     */
    public HomeBase() {
        initComponents();
        writtenComponents();

    }

    private void writtenComponents(){
        ImageIcon homeBaseIcon = new ImageIcon("HomeBaseBackground.png");
        ImageIcon scaledHomeBaseIcon = new ImageIcon(homeBaseIcon.getImage().getScaledInstance(getWidth(), getHeight(), Image.SCALE_FAST));
        HomeBaseBackground.setIcon(scaledHomeBaseIcon);

        itemSellerMenu = new JPopupMenu();
        itemSellerMenu.setBounds(345, 200, 100, 100);
        JMenuItem monsterBall = new JMenuItem(         "Monster Ball           $(price)");
        JMenuItem healthPotion = new JMenuItem(        "Health Potion          $(price)");
        JMenuItem elementalEsPotion = new JMenuItem(   "Potion Es              $(price)");
        JMenuItem elementalAnginPotion = new JMenuItem("Potion Angin           $(price)");
        JMenuItem elementalAirPotion = new JMenuItem(  "Potion Air             $(price)");
        JMenuItem elementalApiPotion = new JMenuItem(  "Potion Api             $(price)");
        JMenuItem elementalTanahPotion = new JMenuItem("Potion Tanah           $(price)");
        itemSellerMenu.add(monsterBall);
        itemSellerMenu.add(healthPotion);
        itemSellerMenu.add(elementalEsPotion);
        itemSellerMenu.add(elementalAnginPotion);
        itemSellerMenu.add(elementalAirPotion);
        itemSellerMenu.add(elementalApiPotion);
        itemSellerMenu.add(elementalTanahPotion);
        this.add(itemSellerMenu);

        ItemSeller.setOpaque(false);
        ItemSeller.setContentAreaFilled(false);
        ItemSeller.setBorderPainted(false);
        ItemSeller.setFocusPainted(false);

        NurseJoy.setOpaque(false);
        NurseJoy.setContentAreaFilled(false);
        NurseJoy.setBorderPainted(false);
        NurseJoy.setFocusPainted(false);

        MonsterStorage.setOpaque(false);
        MonsterStorage.setContentAreaFilled(false);
        MonsterStorage.setBorderPainted(false);
        MonsterStorage.setFocusPainted(false);

        GoToDungeon.setOpaque(false);
        GoToDungeon.setContentAreaFilled(false);
        GoToDungeon.setBorderPainted(false);
        GoToDungeon.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        ItemSeller = new javax.swing.JButton();
        NurseJoy = new javax.swing.JButton();
        MonsterStorage = new javax.swing.JButton();
        GoToDungeon = new javax.swing.JButton();
        HomeBaseBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(790, 500));
        setMinimumSize(new java.awt.Dimension(790, 500));
        setPreferredSize(new java.awt.Dimension(790, 500));
        setResizable(false);

        ItemSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSellerActionPerformed(evt);
            }
        });
        jLayeredPane2.add(ItemSeller);
        ItemSeller.setBounds(150, 100, 80, 80);

        NurseJoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NurseJoyActionPerformed(evt);
            }
        });
        jLayeredPane2.add(NurseJoy);
        NurseJoy.setBounds(390, 150, 72, 70);

        MonsterStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonsterStorageActionPerformed(evt);
            }
        });
        jLayeredPane2.add(MonsterStorage);
        MonsterStorage.setBounds(520, 230, 110, 90);

        GoToDungeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToDungeonActionPerformed(evt);
            }
        });
        jLayeredPane2.add(GoToDungeon);
        GoToDungeon.setBounds(650, 60, 130, 100);

        HomeBaseBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Uer\\Documents\\NetBeansProjects\\Pokemon1\\HomeBaseBackground.png")); // NOI18N
        jLayeredPane2.add(HomeBaseBackground);
        HomeBaseBackground.setBounds(0, 0, 790, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoToDungeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToDungeonActionPerformed
        // TODO add your handling code here:
        BattleMenu battleMenu = new BattleMenu();
        battleMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_GoToDungeonActionPerformed

    private void ItemSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSellerActionPerformed
        // TODO add your handling code here:
        itemSellerMenu.show(this, 335, 200);
    }//GEN-LAST:event_ItemSellerActionPerformed

    private void NurseJoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NurseJoyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NurseJoyActionPerformed

    private void MonsterStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonsterStorageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonsterStorageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoToDungeon;
    private javax.swing.JLabel HomeBaseBackground;
    private javax.swing.JButton ItemSeller;
    private javax.swing.JButton MonsterStorage;
    private javax.swing.JButton NurseJoy;
    private javax.swing.JLayeredPane jLayeredPane2;
    // End of variables declaration//GEN-END:variables
}
